on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Flask server with LocalTunnel
        run:
            python server.py &
            sleep 5
            
            
            lt --port 10000 --print-requests &
            sleep 5
            
            echo "✅ Server and tunnel are running."
            echo "🌐 View your public URL above in the logs."
            
            # Keep the runner alive indefinitely (or until you cancel it)
            tail -f /dev/null